language: php

php:
- 5.6
- 5.5
- 5.4
- 5.3

sudo: false

env:
  global:
  - secure: VyVDCEAexHfV/k4FEToKsVoC23FxT9ngf1UuOnp9ddfr52uHppDnUeHKJ0AMAPsKyPvYCaCHC0+JSOIx2vK2/pZCWkCk12KQ8d4ytPuiNCmnLKn1sOJBn/rcXznE41/DbYA3344dv3wE+W4j4bxD3rJw5NI7NiypnyCp9S6Z6qo=
  - secure: JenTQgFLF8ZgyRvk7y/v2brrJTwEemTcrzG9Brej6U+2mQCthSQIUgYcTsRKKf/VN3nxPK4soPGcx1Y726fLsGPiDR4zyGDEKbFLyz7lFR3N8mybIcaWZOWOx77hmXxzi/XW+UDThSuuRQuWRHubRCpBFB4KaW4dgAq7G7QlYng=

services:
  - redis-server
  - memcached

before_script:
- composer self-update
- travis_retry composer install --prefer-dist --no-interaction
- mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
 - composer require satooshi/php-coveralls:~0.6@stable

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

